/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kusevic.ljetnizadatak.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import kusevic.ljetnizadatak.controller.Obrada;
import kusevic.ljetnizadatak.model.Korisnik;
import kusevic.ljetnizadatak.model.Racun;
import kusevic.ljetnizadatak.model.Radnik;
import kusevic.ljetnizadatak.model.Transakcija;
import kusevic.ljetnizadatak.pomocno.ExcellKlasa;
import kusevic.ljetnizadatak.pomocno.HibernateUtil;

/**
 *
 * @author Tomislav
 */
public class FormaTransakcije extends Forma<Transakcija> {

    private List<Transakcija> listaTransakcija;
    
    private List<Korisnik> rezultatiKorisnik;
    private List<Racun> rezultatiRacun;
    private List<Radnik> rezultatiRadnik;
    private Korisnik korisnik;

    public FormaTransakcije() {
        initComponents();
        nakonInitComponents();
        obrada = new Obrada();
        ucitajTransakcije();
        upisiUListuTransakcija();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        txtUnos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablicaTransakcija = new javax.swing.JTable();
        cbKorisnik = new javax.swing.JCheckBox();
        cbRacun = new javax.swing.JCheckBox();
        cbRadnik = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transakcije");
        setSize(new java.awt.Dimension(200, 200));
        setType(java.awt.Window.Type.UTILITY);

        Panel.setBackground(new java.awt.Color(55, 56, 76));

        txtUnos.setBackground(new java.awt.Color(55, 56, 76));
        txtUnos.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtUnos.setForeground(new java.awt.Color(102, 178, 255));
        txtUnos.setBorder(null);
        txtUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnosActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(55, 56, 76));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kusevic/ljetnizadatak/icons/icons8-Search-50.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablicaTransakcija.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tablicaTransakcija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablicaTransakcija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablicaTransakcijaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablicaTransakcija);

        cbKorisnik.setBackground(new java.awt.Color(55, 56, 76));
        cbKorisnik.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        cbKorisnik.setForeground(new java.awt.Color(102, 178, 255));
        cbKorisnik.setSelected(true);
        cbKorisnik.setText("Korisnik");
        cbKorisnik.setBorder(null);
        cbKorisnik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbKorisnikMouseClicked(evt);
            }
        });

        cbRacun.setBackground(new java.awt.Color(55, 56, 76));
        cbRacun.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        cbRacun.setForeground(new java.awt.Color(102, 178, 255));
        cbRacun.setText("Racun");
        cbRacun.setBorder(null);
        cbRacun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRacunMouseClicked(evt);
            }
        });

        cbRadnik.setBackground(new java.awt.Color(55, 56, 76));
        cbRadnik.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        cbRadnik.setForeground(new java.awt.Color(102, 178, 255));
        cbRadnik.setText("Radnik");
        cbRadnik.setBorder(null);
        cbRadnik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRadnikMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(55, 56, 76));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kusevic/ljetnizadatak/icons/icons8-Microsoft Excel-48.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cbKorisnik)
                .addGap(56, 56, 56)
                .addComponent(cbRacun)
                .addGap(59, 59, 59)
                .addComponent(cbRadnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txtUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKorisnik)
                            .addComponent(cbRacun)
                            .addComponent(cbRadnik))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnosActionPerformed

    private void ucitajTransakcije() {
        listaTransakcija = new ArrayList<>();
        listaTransakcija = HibernateUtil.getSession().createQuery("FROM Transakcija WHERE obrisan=false").list();

    }

    private void upisiUListuTransakcija() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Objekt");
        model.addColumn("Datum");
        model.addColumn("Radnik");
        model.addColumn("Korisnik");
        model.addColumn("Racun");
        model.addColumn("Iznos");

        tablicaTransakcija.setModel(model);
        listaTransakcija.forEach((s) -> {
            model.addRow(new Object[]{s, s.getDatum(), s.getRadnik(), s.getKorisnik(), s.getRacun(), s.getIznos()});
        });
        tablicaTransakcija.getColumnModel().getColumn(0).setWidth(0);
        tablicaTransakcija.getColumnModel().getColumn(0).setMinWidth(0);
        tablicaTransakcija.getColumnModel().getColumn(0).setMaxWidth(0);
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cbKorisnik.isSelected()) {
            if(txtUnos.getText().trim().isEmpty()){
                ucitajTransakcije();
            }else{
            
            rezultatiKorisnik = HibernateUtil.getSession().createQuery("from Korisnik a where a.obrisan=false and concat(a.ime, ' ', a.prezime)"
                    + " like :uvjet").setString("uvjet", "%" + txtUnos.getText() + "%").list();

            for (Korisnik k : rezultatiKorisnik) {

                listaTransakcija = HibernateUtil.getSession().createQuery("from Transakcija a where a.obrisan=false and a.korisnik= :uvjet").setLong("uvjet", k.getSifra()).list();

            }
            }
            
        }
        if(cbRacun.isSelected()){
            if(txtUnos.getText().trim().isEmpty()){
                ucitajTransakcije();
            }else{
            
            rezultatiRacun = HibernateUtil.getSession().createQuery("from Racun a where a.obrisan=false and a.brojRacuna"
                    + " like :uvjet").setString("uvjet", "%" + txtUnos.getText() + "%").list();

            for (Racun r : rezultatiRacun) {

                listaTransakcija = HibernateUtil.getSession().createQuery("from Transakcija a where a.obrisan=false and a.racun= :uvjet").setLong("uvjet", r.getSifra()).list();

            
            }
            }
        }
        if(cbRadnik.isSelected()){
            if(txtUnos.getText().trim().isEmpty()){
                ucitajTransakcije();
            }else{
            rezultatiRadnik = HibernateUtil.getSession().createQuery("from Radnik a where a.obrisan=false and concat(a.ime, ' ', a.prezime)"
                    + " like :uvjet").setString("uvjet", "%" + txtUnos.getText() + "%").list();

            for (Radnik ra : rezultatiRadnik) {

                listaTransakcija = HibernateUtil.getSession().createQuery("from Transakcija a where a.obrisan=false and a.radnik= :uvjet").setLong("uvjet", ra.getSifra()).list();
            }
            }
        }
        
        upisiUListuTransakcija();

    }//GEN-LAST:event_jButton1ActionPerformed

   
    
    
    private void tablicaTransakcijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicaTransakcijaMouseClicked
        entitet = (Transakcija) tablicaTransakcija.getModel().getValueAt(tablicaTransakcija.getSelectedRow(), 0);

    }//GEN-LAST:event_tablicaTransakcijaMouseClicked

    private void cbKorisnikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbKorisnikMouseClicked
        cbKorisnik.setSelected(true);
        cbRacun.setSelected(false);
        cbRadnik.setSelected(false);
    }//GEN-LAST:event_cbKorisnikMouseClicked

    private void cbRacunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRacunMouseClicked
        cbKorisnik.setSelected(false);
        cbRacun.setSelected(true);
        cbRadnik.setSelected(false);
    }//GEN-LAST:event_cbRacunMouseClicked

    private void cbRadnikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRadnikMouseClicked
        cbKorisnik.setSelected(false);
        cbRacun.setSelected(false);
        cbRadnik.setSelected(true);
    }//GEN-LAST:event_cbRadnikMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       ExcellKlasa.exportExcelGrupe(listaTransakcija);
        
       
       
        
    }//GEN-LAST:event_jButton2ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JCheckBox cbKorisnik;
    private javax.swing.JCheckBox cbRacun;
    private javax.swing.JCheckBox cbRadnik;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablicaTransakcija;
    private javax.swing.JTextField txtUnos;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void ucitaj() {
        //only because of 'extands rule'
    }
}
