/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kusevic.ljetnizadatak.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import kusevic.ljetnizadatak.controller.Obrada;
import kusevic.ljetnizadatak.controller.Provjera;
import kusevic.ljetnizadatak.model.RadiNa;
import kusevic.ljetnizadatak.model.Radnik;
import kusevic.ljetnizadatak.model.RadnoMjesto;
import kusevic.ljetnizadatak.pomocno.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Tomislav
 */
public class FormaRadnaMjesta extends Forma<RadnoMjesto> implements EnablingButtons {

    private List<RadnoMjesto> listaRadnoMjesto = new ArrayList();
    private Radnik radnik;
    private List<RadiNa> listaRadiNa = new ArrayList<>();
    private RadnoMjesto radnoMjesto;
    private List<Radnik> sviRadnici = new ArrayList<>();
    private List<Radnik> radniciMjesta = new ArrayList<>();
    private List<Radnik> ostaliRadnici = new ArrayList<>();
    private Session session;
    private RadiNa radiNa;

    public FormaRadnaMjesta(String s) {
        session = HibernateUtil.getSession();
        initComponents();
        nakonInitComponents();
        obrada = new Obrada<>();
        sviRadnici = HibernateUtil.getSession().createQuery("FROM Radnik WHERE obrisan=false").list();
        ucitaj();
        provjeriJelOdabran();

    }

    private List<RadiNa> izvuciRadiNa(Long sifra) {
        listaRadiNa = HibernateUtil.getSession().createQuery("from RadiNa WHERE "
                + " obrisan=false and RadnoMjesto_sifra=:uvjet")
                .setLong("uvjet", sifra).list();
        return listaRadiNa;
    }

    private void ucitajRadnike() {

        if (radniciMjesta == null || radniciMjesta.isEmpty()) {

            DefaultListModel<Radnik> modelMjesta = new DefaultListModel<>();
            lstRadniciNaMjestu.setModel(modelMjesta);
        } else {
            DefaultListModel<Radnik> modelMjesta = new DefaultListModel<>();
            lstRadniciNaMjestu.setModel(modelMjesta);
            for (Radnik a : radniciMjesta) {
                {
                    modelMjesta.addElement(a);
                }
            }
        }

        if (radniciMjesta == null || radniciMjesta.isEmpty()) {
            DefaultListModel<Radnik> modelOstalih = new DefaultListModel<>();

            lstRadnici.setModel(modelOstalih);
            for (Radnik svaki : sviRadnici) {
                modelOstalih.addElement(svaki);
            }

        } else {
            DefaultListModel<Radnik> modelOstalih = new DefaultListModel<>();

            lstRadnici.setModel(modelOstalih);
            boolean naden = false;
            for (Radnik svaki : sviRadnici) {
                naden = false;
                for (Radnik izMjesta : radniciMjesta) {
                    if (svaki.getSifra().equals(izMjesta.getSifra())) {

                        naden = true;
                        break;
                    }

                }

                if (!naden) {
                    modelOstalih.addElement(svaki);

                }

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablicaMjesta = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRadnici = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstRadniciNaMjestu = new javax.swing.JList<>();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tekstOdjel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNaziv = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUnos = new javax.swing.JButton();
        btnPromjena = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();
        greskoNaziv = new javax.swing.JLabel();
        greskoOdjel = new javax.swing.JLabel();
        txtOdjel = new javax.swing.JTextField();
        tekstNaziv = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Radno mjesto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(38, 40, 55));

        tablicaMjesta.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        tablicaMjesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablicaMjesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablicaMjestaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablicaMjesta);

        lstRadnici.setBackground(new java.awt.Color(38, 40, 55));
        lstRadnici.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        lstRadnici.setForeground(new java.awt.Color(102, 178, 255));
        lstRadnici.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRadniciValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstRadnici);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 178, 255));
        jLabel4.setText("OSTALI RADNICI");

        lstRadniciNaMjestu.setBackground(new java.awt.Color(38, 40, 55));
        lstRadniciNaMjestu.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        lstRadniciNaMjestu.setForeground(new java.awt.Color(102, 178, 255));
        jScrollPane3.setViewportView(lstRadniciNaMjestu);

        btnRight.setText(">>");
        btnRight.setHideActionText(true);
        btnRight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRight.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnLeft.setText("<<");
        btnLeft.setHideActionText(true);
        btnLeft.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLeft.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 178, 255));
        jLabel5.setText("RADNICI MJESTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(55, 56, 76));

        tekstOdjel.setBackground(new java.awt.Color(55, 56, 76));
        tekstOdjel.setForeground(new java.awt.Color(204, 204, 204));
        tekstOdjel.setBorder(null);

        txtNaziv.setBackground(new java.awt.Color(55, 56, 76));
        txtNaziv.setForeground(new java.awt.Color(204, 204, 204));
        txtNaziv.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 178, 255));
        jLabel1.setText("NAZIV");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 178, 255));
        jLabel2.setText("ODJEL");

        btnUnos.setBackground(new java.awt.Color(55, 56, 76));
        btnUnos.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnUnos.setForeground(new java.awt.Color(102, 178, 255));
        btnUnos.setText("UNOS");
        btnUnos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        btnPromjena.setBackground(new java.awt.Color(55, 56, 76));
        btnPromjena.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnPromjena.setForeground(new java.awt.Color(102, 178, 255));
        btnPromjena.setText("PROMJENA");
        btnPromjena.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPromjena.setEnabled(false);
        btnPromjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjenaActionPerformed(evt);
            }
        });

        btnBrisanje.setBackground(new java.awt.Color(55, 56, 76));
        btnBrisanje.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnBrisanje.setForeground(new java.awt.Color(102, 178, 255));
        btnBrisanje.setText("BRISANJE");
        btnBrisanje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBrisanje.setEnabled(false);
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        greskoNaziv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        greskoNaziv.setForeground(new java.awt.Color(255, 0, 0));

        greskoOdjel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        greskoOdjel.setForeground(new java.awt.Color(255, 0, 0));

        txtOdjel.setBackground(new java.awt.Color(55, 56, 76));
        txtOdjel.setForeground(new java.awt.Color(204, 204, 204));
        txtOdjel.setBorder(null);

        tekstNaziv.setBackground(new java.awt.Color(55, 56, 76));
        tekstNaziv.setForeground(new java.awt.Color(204, 204, 204));
        tekstNaziv.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(379, 379, 379)
                                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtOdjel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tekstOdjel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(greskoNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromjena, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(504, Short.MAX_VALUE)
                    .addComponent(greskoOdjel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(tekstNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(371, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOdjel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tekstOdjel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(greskoNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPromjena, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(greskoOdjel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addGap(320, 320, 320)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addComponent(tekstNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(419, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed

        if (Provjera.provjeriJelText(tekstOdjel.getText()) == false) {
            greskoOdjel.setText("ERROR");
        }
        if (Provjera.provjeriJelText(tekstNaziv.getText()) == false) {
            greskoNaziv.setText("ERROR");
        }
        if (Provjera.provjeriJelText(tekstNaziv.getText()) == true && Provjera.provjeriJelText(tekstOdjel.getText()) == true) {
            entitet = new RadnoMjesto();

            spremi();
            ucitaj();
        }


    }//GEN-LAST:event_btnUnosActionPerformed
    @Override
    protected void spremi() {
        entitet.setOdjel(tekstOdjel.getText().substring(0, 1).toUpperCase() + tekstOdjel.getText().substring(1).toLowerCase());
        entitet.setNaziv(tekstNaziv.getText().substring(0, 1).toUpperCase() + tekstNaziv.getText().substring(1).toLowerCase());
        super.spremi();

    }

    @Override
    public void provjeriJelOdabran() {
        tablicaMjesta.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            btnPromjena.setEnabled(true);
            btnBrisanje.setEnabled(true);
        });
    }


    private void btnPromjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjenaActionPerformed
        spremi();
        ucitaj();
    }//GEN-LAST:event_btnPromjenaActionPerformed

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        entitet.setObrisan(true);
        spremi();
        ucitaj();
    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void tablicaMjestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicaMjestaMouseClicked

        if (tablicaMjesta.getValueAt(tablicaMjesta.getSelectedRow(), 0) == null) {
            System.out.println("nista nije oznaceno na tblici mjesta");
            return;
        }
        entitet = (RadnoMjesto) tablicaMjesta.getValueAt(tablicaMjesta.getSelectedRow(), 0);
        tekstNaziv.setText(entitet.getNaziv());
        tekstOdjel.setText(entitet.getOdjel());
        listaRadiNa = izvuciRadiNa(entitet.getSifra());
        radniciMjesta = new ArrayList<>();
        for (RadiNa rn : listaRadiNa) {
            radniciMjesta.add(rn.getRadnik());
        }
        ucitajRadnike();
        lstRadnici.repaint();
        lstRadniciNaMjestu.repaint();
    }//GEN-LAST:event_tablicaMjestaMouseClicked

    private void lstRadniciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRadniciValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        if (lstRadnici.getSelectedValue() == null) {
            return;
        }

        radnik = new Radnik();
        radnik = lstRadnici.getSelectedValue();


    }//GEN-LAST:event_lstRadniciValueChanged

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed

        radiNa = new RadiNa();
        radiNa.setPocetakRada(new Date());
        radiNa.setRadnik(radnik);
        radiNa.setRadnoMjesto(entitet);
        radiNa = spremiRadiNa(radiNa);
        radnik = lstRadnici.getSelectedValue();

        listaRadiNa.add(radiNa);
        entitet.setRadnici(listaRadiNa);

        radniciMjesta.add(radnik);
        ucitajRadnike();
        lstRadnici.repaint();
        lstRadniciNaMjestu.repaint();
    }//GEN-LAST:event_btnRightActionPerformed

    public RadiNa spremiRadiNa(RadiNa entitet) {
        Date d = new Date();

        if (entitet.getSifra() == null) {
            entitet.setDatumKreiranja(d);
            entitet.setObrisan(false);
        }
        entitet.setDatumPromjene(d);
        session.beginTransaction();
        session.saveOrUpdate(entitet);
        session.getTransaction().commit();
        return entitet;
    }


    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed

        radnik = (lstRadniciNaMjestu.getSelectedValue());

        radnoMjesto = ((RadnoMjesto) tablicaMjesta.getModel().getValueAt(tablicaMjesta.getSelectedRow(), 0));

        listaRadiNa = HibernateUtil.getSession().createQuery("FROM RadiNa WHERE obrisan=false AND radnoMjesto_sifra=? and radnik_sifra=? ").setParameter(0, radnoMjesto.getSifra()).setParameter(1, radnik.getSifra()).list();
        radiNa = listaRadiNa.get(0);
        radiNa.setObrisan(true);
        radiNa = spremiRadiNa(radiNa);

        listaRadiNa = izvuciRadiNa(entitet.getSifra());
        System.out.println();
        radniciMjesta = new ArrayList<>();
        for (RadiNa rn : listaRadiNa) {
            radniciMjesta.add(rn.getRadnik());
        }
        ucitajRadnike();
        lstRadnici.repaint();
        lstRadniciNaMjestu.repaint();

        ucitajRadnike();
        lstRadnici.repaint();
        lstRadniciNaMjestu.repaint();
        //ponovno oznaci isto radno mjesto

    }//GEN-LAST:event_btnLeftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnPromjena;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnUnos;
    private javax.swing.JLabel greskoNaziv;
    private javax.swing.JLabel greskoOdjel;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<Radnik> lstRadnici;
    private javax.swing.JList<Radnik> lstRadniciNaMjestu;
    private javax.swing.JTable tablicaMjesta;
    private javax.swing.JTextField tekstNaziv;
    private javax.swing.JTextField tekstOdjel;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtOdjel;
    // End of variables declaration//GEN-END:variables

    

    @Override
    protected void ucitaj() {

        ucitajRadnike();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Objekt");
        model.addColumn("Odjel");
        model.addColumn("Naziv");
        tablicaMjesta.setModel(model);
        listaRadnoMjesto = HibernateUtil.getSession().createQuery("FROM RadnoMjesto WHERE obrisan=false").list();
        listaRadnoMjesto.forEach((s) -> {
            model.addRow(new Object[]{s, s.getOdjel(), s.getNaziv()});
        });
        tablicaMjesta.getColumnModel().getColumn(0).setWidth(0);
        tablicaMjesta.getColumnModel().getColumn(0).setMinWidth(0);
        tablicaMjesta.getColumnModel().getColumn(0).setMaxWidth(0);

    }

}
