/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kusevic.ljetnizadatak.view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Tomislav
 */
public class Ucitavanje extends javax.swing.JFrame {

    /**
     * Creates new form Load
     */
    public Ucitavanje() {

        initComponents();
        
        txtRigths.setText("This program is personal application projected by Tomislav Kušević."+ "\n"+ " All rights reserved. It is allowed to use the code with source reference "+ 
                "\n"+"Application is based on Java sowftware, SQL database, with Hibernate. "+"\n"+"The application is intended for banking processes and easier manipulation of users and transactions.");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setVisible(true);
        for (int i = 0; i <= 100; i++) {
            try {
                Thread.sleep(40);
                lblPosto.setText(i + "%");
                pbLoad.setValue(i);
                if (i == 100) {
                    this.setVisible(false);
                }
                if (i == 60) {
                    Thread.sleep(100);
                    lblStatus.setText("Loading modules...");
                }
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNaslov = new javax.swing.JTextField();
        pbLoad = new javax.swing.JProgressBar();
        lblPosto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNaslov1 = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRigths = new javax.swing.JTextPane();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 56, 76));

        txtNaslov.setBackground(new java.awt.Color(55, 56, 76));
        txtNaslov.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtNaslov.setForeground(new java.awt.Color(102, 178, 255));
        txtNaslov.setText("to your Bank!");
        txtNaslov.setBorder(null);
        txtNaslov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaslovActionPerformed(evt);
            }
        });

        pbLoad.setForeground(new java.awt.Color(255, 102, 102));

        lblPosto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPosto.setForeground(new java.awt.Color(102, 178, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kusevic/ljetnizadatak/icons/icons8-Registered Trademark-48.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        txtNaslov1.setBackground(new java.awt.Color(55, 56, 76));
        txtNaslov1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtNaslov1.setForeground(new java.awt.Color(102, 178, 255));
        txtNaslov1.setText("WELCOME ");
        txtNaslov1.setBorder(null);
        txtNaslov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaslov1ActionPerformed(evt);
            }
        });

        lblStatus.setForeground(new java.awt.Color(102, 178, 255));
        lblStatus.setText("Unpacking modules...");

        txtRigths.setBackground(new java.awt.Color(55, 56, 76));
        txtRigths.setBorder(null);
        txtRigths.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        txtRigths.setForeground(new java.awt.Color(255, 102, 102));
        txtRigths.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtRigths);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPosto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(lblStatus)
                .addGap(0, 8, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(pbLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(txtNaslov1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPosto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(txtNaslov1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNaslovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaslovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaslovActionPerformed

    private void txtNaslov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaslov1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaslov1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPosto;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JProgressBar pbLoad;
    private javax.swing.JTextField txtNaslov;
    private javax.swing.JTextField txtNaslov1;
    private javax.swing.JTextPane txtRigths;
    // End of variables declaration//GEN-END:variables
}
